/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tictactoegame;

import java.awt.Color;
import java.util.Random;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author abdelrahman
 */
public class FrmTicTacToeGame extends javax.swing.JFrame {

    private String whoseTurn = "X";
    private String one = "", two = "", three = "", four = "", five = "", six = "", seven = "", eight = "", nine = "";
    private Random rand;

    /**
     * Creates new form FrmTicTacToeGame
     */
    public FrmTicTacToeGame() {
        initComponents();
        setSize(600, 600);
        setLocationRelativeTo(this);
        rand = new Random();

        // playRopot();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelGrid = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jButton9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelGrid.setMinimumSize(new java.awt.Dimension(600, 600));
        jPanelGrid.setPreferredSize(new java.awt.Dimension(600, 600));
        jPanelGrid.setLayout(new java.awt.GridLayout(3, 3));

        jPanel1.setMinimumSize(new java.awt.Dimension(35, 11));
        jPanel1.setPreferredSize(new java.awt.Dimension(35, 11));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, java.awt.BorderLayout.CENTER);

        jPanelGrid.add(jPanel1);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, java.awt.BorderLayout.CENTER);

        jPanelGrid.add(jPanel2);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3, java.awt.BorderLayout.CENTER);

        jPanelGrid.add(jPanel3);

        jPanel4.setLayout(new java.awt.BorderLayout());

        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton4, java.awt.BorderLayout.CENTER);

        jPanelGrid.add(jPanel4);

        jPanel5.setLayout(new java.awt.BorderLayout());

        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton5, java.awt.BorderLayout.CENTER);

        jPanelGrid.add(jPanel5);

        jPanel6.setLayout(new java.awt.BorderLayout());

        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton6, java.awt.BorderLayout.CENTER);

        jPanelGrid.add(jPanel6);

        jPanel7.setLayout(new java.awt.BorderLayout());

        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton7, java.awt.BorderLayout.CENTER);

        jPanelGrid.add(jPanel7);

        jPanel8.setLayout(new java.awt.BorderLayout());

        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton8, java.awt.BorderLayout.CENTER);

        jPanelGrid.add(jPanel8);

        jPanel9.setLayout(new java.awt.BorderLayout());

        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton9, java.awt.BorderLayout.CENTER);

        jPanelGrid.add(jPanel9);

        getContentPane().add(jPanelGrid, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if (jButton1.getText() == "") {
            jButton1.setText(whoseTurn);

            if (whoseTurn.equalsIgnoreCase("X")) {
                jButton1.setForeground(Color.red);
            } else {
                jButton1.setForeground(Color.BLUE);
            }
            determineWhoseTurn();
            determineIfWin();
            ReDraw();
    //        playRopot();
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        if (jButton2.getText() == "") {
            jButton2.setText(whoseTurn);

            if (whoseTurn.equalsIgnoreCase("X")) {
                jButton2.setForeground(Color.red);
            } else {
                jButton2.setForeground(Color.BLUE);
            }

            determineWhoseTurn();
            determineIfWin();
            ReDraw();
    //        playRopot();
        }
    }//GEN-LAST:event_jButton2ActionPerformed


    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (jButton3.getText() == "") {
            jButton3.setText(whoseTurn);

            if (whoseTurn.equalsIgnoreCase("X")) {
                jButton3.setForeground(Color.red);
            } else {
                jButton3.setForeground(Color.BLUE);
            }
            determineWhoseTurn();
            determineIfWin();
            ReDraw();
    //        playRopot();
        }
    }//GEN-LAST:event_jButton3ActionPerformed


    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (jButton4.getText() == "") {
            jButton4.setText(whoseTurn);

            if (whoseTurn.equalsIgnoreCase("X")) {
                jButton4.setForeground(Color.red);
            } else {
                jButton4.setForeground(Color.BLUE);
            }
            determineWhoseTurn();
            determineIfWin();
            ReDraw();
       //     playRopot();
        }
    }//GEN-LAST:event_jButton4ActionPerformed


    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if (jButton5.getText() == "") {
            jButton5.setText(whoseTurn);

            if (whoseTurn.equalsIgnoreCase("X")) {
                jButton5.setForeground(Color.red);
            } else {
                jButton5.setForeground(Color.BLUE);
            }
            determineWhoseTurn();
            determineIfWin();
            ReDraw();
       //     playRopot();
        }
    }//GEN-LAST:event_jButton5ActionPerformed


    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if (jButton6.getText() == "") {
            jButton6.setText(whoseTurn);

            if (whoseTurn.equalsIgnoreCase("X")) {
                jButton6.setForeground(Color.red);
            } else {
                jButton6.setForeground(Color.BLUE);
            }
            determineWhoseTurn();
            determineIfWin();
            ReDraw();
           // playRopot();
        }
    }//GEN-LAST:event_jButton6ActionPerformed


    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        if (jButton7.getText() == "") {
            jButton7.setText(whoseTurn);

            if (whoseTurn.equalsIgnoreCase("X")) {
                jButton7.setForeground(Color.red);
            } else {
                jButton7.setForeground(Color.BLUE);
            }
            determineWhoseTurn();
            determineIfWin();
            ReDraw();
         //   playRopot();
        }
    }//GEN-LAST:event_jButton7ActionPerformed


    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed

        setText(jButton8);
      //  playRopot();
      //  NewJPanel p = new NewJPanel();
        
     //   p.setSize(600,600);
    ///    jPanelGrid.removeAll();
     //   jPanelGrid.add(p);

    }//GEN-LAST:event_jButton8ActionPerformed


    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed

        if (jButton9.getText() == "") {
            jButton9.setText(whoseTurn);

            if (whoseTurn.equalsIgnoreCase("X")) {
                jButton9.setForeground(Color.red);
            } else {
                jButton9.setForeground(Color.BLUE);
            }
            determineWhoseTurn();
            determineIfWin();
            ReDraw();
           // playRopot();
        } else {
            System.out.println(jButton9.getText());
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    /*
    * A method use to check buttons is empty or not
     */
    private void ReDraw() {
        String one = jButton1.getText();
        String two = jButton2.getText();
        String three = jButton3.getText();
        String four = jButton4.getText();
        String five = jButton5.getText();
        String six = jButton6.getText();
        String seven = jButton7.getText();
        String eight = jButton8.getText();
        String nine = jButton9.getText();

        if (one != "" && two != "" && three != "" && four != "" && five != "" && six != "" && seven != "" && eight != "" && nine != "") {
            JOptionPane.showMessageDialog(this, "The match has been drawn !!!", "Match result", JOptionPane.INFORMATION_MESSAGE);
            resetGame();
        }

    }

    private void determineWhoseTurn() {
        if (whoseTurn.equalsIgnoreCase("X")) {
            whoseTurn = "O";
        } else {
            whoseTurn = "X";
        }

    }

    private void xWins() {
        JOptionPane.showMessageDialog(this, "X WINS", "Winner", JOptionPane.INFORMATION_MESSAGE);
        resetGame();
    }

    private void oWins() {
        JOptionPane.showMessageDialog(this, "O WINS", "Winner", JOptionPane.INFORMATION_MESSAGE);
        resetGame();
    }

    private void resetGame() {
        jButton1.setText("");
        jButton2.setText("");
        jButton3.setText("");
        jButton4.setText("");
        jButton5.setText("");
        jButton6.setText("");
        jButton7.setText("");
        jButton8.setText("");
        jButton9.setText("");
    }

    private void determineIfWin() {

        one = jButton1.getText();
        two = jButton2.getText();
        three = jButton3.getText();
        four = jButton4.getText();
        five = jButton5.getText();
        six = jButton6.getText();
        seven = jButton7.getText();
        eight = jButton8.getText();
        nine = jButton9.getText();

        if (one == "X" && two == "X" && three == "X") {
            xWins();
        }
        if (four == "X" && five == "X" && six == "X") {
            xWins();
        }
        if (seven == "X" && eight == "X" && nine == "X") {
            xWins();
        }
        if (one == "X" && two == "X" && three == "X") {
            xWins();
        }
        if (one == "X" && four == "X" && seven == "X") {
            xWins();
        }
        if (two == "X" && five == "X" && eight == "X") {
            xWins();
        }
        if (three == "X" && six == "X" && nine == "X") {
            xWins();
        }
        if (one == "X" && five == "X" && nine == "X") {
            xWins();
        }
        if (seven == "X" && five == "X" && three == "X") {
            xWins();
        }

        // if o wins 
        if (one == "O" && two == "O" && three == "O") {
            oWins();
        }
        if (four == "o" && five == "O" && six == "O") {
            oWins();
        }
        if (seven == "O" && eight == "O" && nine == "O") {
            oWins();
        }
        if (one == "O" && two == "O" && three == "O") {
            oWins();
        }
        if (one == "O" && four == "O" && seven == "O") {
            oWins();
        }
        if (two == "O" && five == "O" && eight == "O") {
            oWins();
        }
        if (three == "O" && six == "O" && nine == "O") {
            oWins();
        }
        if (one == "O" && five == "O" && nine == "O") {
            oWins();
        }
        if (seven == "O" && five == "O" && three == "O") {
            oWins();
        }

    }

    private void playRopot() {

        while (true) {
            int position = genRandmInt();
            System.out.println(position);

            if (poistionIsEmptyOrNot(position)) {
                setTextInBtn(position);
                System.out.println("empty");
                break;
            } else {
                System.out.println("no empty");
            }
        }
    }

    private void setText(JButton btn) {

        if (btn.getText() == "") {
            btn.setText(whoseTurn);

            if (whoseTurn.equalsIgnoreCase("X")) {

                btn.setForeground(Color.red);
            } else {
                btn.setForeground(Color.BLUE);
            }
            determineWhoseTurn();
            determineIfWin();
            ReDraw();
        }

    }

    private void setTextInBtn(int position) {

        switch (position) {
            case 1:
                if (one == "") {
                    setText(jButton1);
                }
                break;
            case 2:
                if (two == "") {
                    setText(jButton2);
                }
                break;
            case 3:
                if (three == "") {
                    setText(jButton3);
                }
                break;
            case 4:
                if (four == "") {
                    setText(jButton4);
                }
                break;
            case 5:
                if (five == "") {
                    setText(jButton5);
                }
                break;
            case 6:
                if (six == "") {
                    setText(jButton6);
                }
                break;
            case 7:
                if (seven == "") {
                    setText(jButton7);
                }
                break;
            case 8:
                if (eight == "") {
                    setText(jButton8);
                }
                break;
            case 9:
                if (nine == "") {
                    setText(jButton9);
                }
                break;
        }

    }

    private boolean poistionIsEmptyOrNot(int position) {

        boolean isEmpty = false;

        switch (position) {
            case 1:
                if (one == "") {
                    isEmpty = true;
                }
                break;
            case 2:
                if (two == "") {
                    isEmpty = true;
                }
                break;
            case 3:
                if (three == "") {
                    isEmpty = true;
                }
                break;
            case 4:
                if (four == "") {
                    isEmpty = true;
                }
                break;
            case 5:
                if (five == "") {
                    isEmpty = true;
                }
                break;
            case 6:
                if (six == "") {
                    isEmpty = true;
                }
                break;
            case 7:
                if (seven == "") {
                    isEmpty = true;
                }
                break;
            case 8:
                if (eight == "") {
                    isEmpty = true;
                }
                break;
            case 9:
                if (nine == "") {
                    isEmpty = true;
                }
                break;
        }

        return isEmpty;
    }

    private int genRandmInt() {
        return rand.nextInt((9 - 1) + 1) + 1;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmTicTacToeGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmTicTacToeGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmTicTacToeGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmTicTacToeGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmTicTacToeGame().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelGrid;
    // End of variables declaration//GEN-END:variables
}
