/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package xo_game;

import model.IntializeSocket;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Player;

/**
 *
 * @author mai
 */
public class LogIn extends javax.swing.JFrame {

    IntializeSocket intializeSocket;
    String replyMsg;

    public LogIn() {
        initComponents();
        show_password_label.setVisible(false);
        replyMsg = "0";
        intializeSocket = new IntializeSocket();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        back_label1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        user_name_txt_login = new javax.swing.JTextField();
        password_txt_login = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        forget_password_label_login = new javax.swing.JLabel();
        sign_up_button_login = new javax.swing.JButton();
        log_in_button_login = new javax.swing.JButton();
        exit_label = new javax.swing.JLabel();
        show_password_label = new javax.swing.JLabel();
        invisible_password_label = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jPanel2.setBackground(new java.awt.Color(120, 0, 46));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/circle-cropped.png"))); // NOI18N

        back_label1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back.png"))); // NOI18N
        back_label1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                back_label1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(back_label1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel4)
                .addContainerGap(61, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(back_label1)
                .addGap(106, 106, 106)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(186, 79, 84));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        user_name_txt_login.setBackground(new java.awt.Color(186, 79, 84));
        user_name_txt_login.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        user_name_txt_login.setForeground(new java.awt.Color(255, 255, 255));
        user_name_txt_login.setToolTipText("");
        user_name_txt_login.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        user_name_txt_login.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                user_name_txt_loginFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                user_name_txt_loginFocusLost(evt);
            }
        });
        user_name_txt_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_name_txt_loginActionPerformed(evt);
            }
        });
        jPanel3.add(user_name_txt_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 190, 30));

        password_txt_login.setBackground(new java.awt.Color(186, 79, 84));
        password_txt_login.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        password_txt_login.setForeground(new java.awt.Color(255, 255, 255));
        password_txt_login.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        password_txt_login.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                password_txt_loginFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                password_txt_loginFocusLost(evt);
            }
        });
        jPanel3.add(password_txt_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 190, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user.png"))); // NOI18N
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 20, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lock.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 20, 30));

        forget_password_label_login.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        forget_password_label_login.setForeground(new java.awt.Color(255, 255, 255));
        forget_password_label_login.setText("Does not have an account?");
        forget_password_label_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                forget_password_label_loginMouseClicked(evt);
            }
        });
        jPanel3.add(forget_password_label_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 460, 270, -1));

        sign_up_button_login.setBackground(new java.awt.Color(255, 255, 255));
        sign_up_button_login.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        sign_up_button_login.setForeground(new java.awt.Color(120, 0, 46));
        sign_up_button_login.setText("Sign Up");
        sign_up_button_login.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(120, 0, 46), 20));
        sign_up_button_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sign_up_button_loginActionPerformed(evt);
            }
        });
        jPanel3.add(sign_up_button_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 500, 370, 130));

        log_in_button_login.setBackground(new java.awt.Color(255, 255, 255));
        log_in_button_login.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        log_in_button_login.setForeground(new java.awt.Color(120, 0, 46));
        log_in_button_login.setText("Log In");
        log_in_button_login.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(120, 0, 46), 20));
        log_in_button_login.setPreferredSize(new java.awt.Dimension(195, 100));
        log_in_button_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                log_in_button_loginActionPerformed(evt);
            }
        });
        jPanel3.add(log_in_button_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 370, 130));

        exit_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-close-window-40.png"))); // NOI18N
        exit_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit_labelMouseClicked(evt);
            }
        });
        jPanel3.add(exit_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, 40, 40));

        show_password_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-eye-20.png"))); // NOI18N
        show_password_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                show_password_labelMouseClicked(evt);
            }
        });
        jPanel3.add(show_password_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 210, -1, -1));

        invisible_password_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-invisible-20.png"))); // NOI18N
        invisible_password_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                invisible_password_labelMouseClicked(evt);
            }
        });
        jPanel3.add(invisible_password_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 210, 20, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Username");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 130, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 120, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 891, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void log_in_button_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_log_in_button_loginActionPerformed
        String userName = user_name_txt_login.getText();
        String password = password_txt_login.getText();

        System.out.println(userName + " " + " " + password + " ");

        //go to user Profile
        intializeSocket.getPs().println("logIn" + "#" + userName + "#" + password);

        try {
            replyMsg = intializeSocket.getDis().readLine();
            System.out.println("replyMeg = " + replyMsg);

            if (replyMsg.charAt(0) == '1') {
                Player.setUserName(replyMsg.substring(1));
                System.out.println(Player.getUserName());
                user_profile up = new user_profile();
                up.setVisible(true);
                this.setVisible(false);
            } else {
                System.out.println("error");

            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Connect to server");
        }

    }//GEN-LAST:event_log_in_button_loginActionPerformed

    private void sign_up_button_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sign_up_button_loginActionPerformed
        //TODO add your handling code here:
        //go to sign up form
        Regist reg = new Regist();
        reg.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_sign_up_button_loginActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked

    private void forget_password_label_loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forget_password_label_loginMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_forget_password_label_loginMouseClicked

    private void user_name_txt_loginFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_user_name_txt_loginFocusGained
        // TODO add your handling code here:
      
    }//GEN-LAST:event_user_name_txt_loginFocusGained

    private void user_name_txt_loginFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_user_name_txt_loginFocusLost
        // TODO add your handling code here:
    
    }//GEN-LAST:event_user_name_txt_loginFocusLost

    private void password_txt_loginFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_password_txt_loginFocusGained
        // TODO add your handling code here:
        if (password_txt_login.getText().equals("password")) {
            password_txt_login.setText("");
        }

    }//GEN-LAST:event_password_txt_loginFocusGained

    private void password_txt_loginFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_password_txt_loginFocusLost
        // TODO add your handling code here:


    }//GEN-LAST:event_password_txt_loginFocusLost

    private void user_name_txt_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user_name_txt_loginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_user_name_txt_loginActionPerformed

    private void exit_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit_labelMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exit_labelMouseClicked

    private void back_label1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_label1MouseClicked
        // TODO add your handling code here:
        Start st = new Start();
        st.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_back_label1MouseClicked

    private void show_password_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_show_password_labelMouseClicked
        // TODO add your handling code here:
        //show password here
        invisible_password_label.setVisible(true);
        show_password_label.setVisible(false);
        password_txt_login.setEchoChar('*');
        
    }//GEN-LAST:event_show_password_labelMouseClicked

    private void invisible_password_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_invisible_password_labelMouseClicked
        // TODO add your handling code here:

        show_password_label.setVisible(true);
        invisible_password_label.setVisible(false);
        password_txt_login.setEchoChar((char)0);
        

    }//GEN-LAST:event_invisible_password_labelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back_label1;
    private javax.swing.JLabel exit_label;
    private javax.swing.JLabel forget_password_label_login;
    private javax.swing.JLabel invisible_password_label;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton log_in_button_login;
    private javax.swing.JPasswordField password_txt_login;
    private javax.swing.JLabel show_password_label;
    private javax.swing.JButton sign_up_button_login;
    private javax.swing.JTextField user_name_txt_login;
    // End of variables declaration//GEN-END:variables

}
